### ISSUE TITLE
Why not use IDNA?

### ISSUE THREAD

**Issue by aartaka** [Shinmera/punycode#1]
Hi!

I've commented about it on Mastodon, but my comment has likely gotten auto-deleted before you've seen it :D 

Why don't you use [IDNA](https://github.com/antifuchs/idna)? Seems to implement roughly the same logic already. Is there some additional benefit of `punycode` over IDNA that I'm unaware of?

EDIT: messed up plural :D

**Comment by Shinmera** [comment]
It was mentioned in the other replies in the same toot thread that you didn't read.

https://mastodon.tymoon.eu/@shinmera/110300971237557977
